### ISSUE TITLE
REQUIRED: AceBook should run on Heroku or AWS

### ISSUE THREAD

**Issue by DaveLawes** [ChocolatineMathou/acebook-PushMePullYou#17]
Heroku - nice readable docs, lots of magic under the hood
AWS - good docs, but slightly more challenging to set up

**Comment by DaveLawes** [comment]
This is blocked until we encrypt data

**Comment by ChocolatineMathou** [comment]
master branch is running on Heroku, automatic deployment is set up
https://acebook-pushmepullyou.herokuapp.com/
